server:
  port: 8088
  servlet:
    session:
      timeout: 180S
spring:
  datasource:
    url: jdbc:mysql://localhost/shopdemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
